language: php
php:
  - '5.5'
  - '5.6'
service:
  - mysql
install:
  - mysql -u root < scripts/bd.sql
  - composer install
script:
  - vendor/bin/phpunit
notifications:
  email:
    - absmarcosdalte@gmail.com
