language: php
php:
  - '5.5'
  - '5.6'
service:
  - mysql
install:
  - composer install
before_install:
  - mysql -e scripts/bd.sql
script:
  - vendor/bin/phpunit
notifications:
  email:
    - absmarcosdalte@gmail.com
