language: php
php:
  - '5.5'
  - '5.6'
service:
  - mysql
install:
  - composer install
before_install:
  - mysql -e 'CREATE DATABASE baladay;'  
script:
  - vendor/bin/phpunit
notifications:
  email:
    - absmarcosdalte@gmail.com
